# [server]
# relay="127.0.0.1:8080"
# cert_file=""
# key_file=""
# cert_email="abc@email.com"


[client]
address="aa.bb.cc"

[client.http_proxy]
address=":8080"

[client.dns]
redirect_ip="127.0.0.1"
relay="" # empty to dynamic detect
flush_cmd="" # macOS: pkill mDNSResponder || true, Windows: ipconfig /flushdnss

# [client.router.port_mapping]
# ":2222"="aa.bb.cc:22"

[client.router]
detect_level=2 # 0~4, the bigger the harder to add
detect_timeout="300ms"

proxy_list=[
    "**.google.*", # google
    "**.goo.gl",
    "**.googleusercontent.com",
    "**.googleapis.com",
    "*.googlesource.com",
    "**.youtube.com", # youtube
    "**.ytimg.com",
    "**.ggpht.com",
    "**.googlevideo.com",
    "**.facebook.com", # facebook
    "**.fbcdn.net",
    "**.twitter.com", # twitter
    "**.twimg.com",
    "**.blogspot.com", # blogspot
    "**.appspot.com",
    "**.wikipedia.org", # wikipeida
    "*.cloudfront.net",
    "**.amazon.com",
    "**.amazonaws.com",
    "*.githubusercontent.com",
    "*.github.*",
]
direct_list=[
    "**.in-addr.arpa",
    "imap.*.*",
    "imap.*.*.*",
    "smtp.*.*",
    "smtp.*.*.*",
    "pop.*.*",
    "pop.*.*.*",
    "imap-mail.outlook.com",
    "**.qq.com",
    "**.baidu.com",
    "*.aliyun.com",
    "**.cn",
    "**.icloud.com",
    "**.163.com",
    "**.weiyun.com",
]
