[upstream]
socks5="127.0.0.1:1080"
dns="" # eg: 223.5.5.5, keep empty to get it from network environment

[downstream]
serve_ip="127.0.0.1"
http_proxy="" # eg: :8080, 127.0.0.1:8080, keep empty to disable it

[router.port_mapping]
# 2222="aaa.bbb.cc:22"

[router]
flush_dns_cmd="" # Platform-related, keep empty to use default command
proxy_level=2 # dynamic detect level, (0~4), more bigger more harder to be proxy
proxy_list=[
    "**.google.*", # google
    "**.goo.gl",
    "**.googleusercontent.com",
    "**.googleapis.com",
    "*.googlesource.com",
    "**.youtube.com", # youtube
    "**.ytimg.com",
    "**.ggpht.com",
    "**.googlevideo.com",
    "**.facebook.com", # facebook
    "**.fbcdn.net",
    "**.twitter.com", # twitter
    "**.twimg.com",
    "**.blogspot.com", # blogspot
    "**.appspot.com",
    "**.wikipedia.org", # wikipeida
    "*.cloudfront.net",
    "**.amazon.com",
    "**.amazonaws.com",
    "*.githubusercontent.com",
    "*.github.*",
]
direct_list=[
    "**.in-addr.arpa",
    "imap.*.*",
    "imap.*.*.*",
    "smtp.*.*",
    "smtp.*.*.*",
    "pop.*.*",
    "pop.*.*.*",
    "imap-mail.outlook.com",
    "**.qq.com",
    "**.baidu.com",
    "*.aliyun.com",
    "**.cn",
    "**.icloud.com",
    "**.163.com",
    "**.weiyun.com",
]
