name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2

      - name: build matrix
        run: |
          cp conf/sower.toml sower.toml

          GOOS=linux GOARCH=amd64 make build
          tar czvf sower-linux-amd64.tar.gz sower sower.toml
          GOOS=linux GOARCH=386 make build
          tar czvf sower-linux-386.tar.gz sower sower.toml
          GOOS=linux GOARCH=arm make build
          tar czvf sower-linux-arm.tar.gz sower sower.toml
          GOOS=linux GOARCH=arm64 make build
          tar czvf sower-linux-arm64.tar.gz sower sower.toml
          GOOS=linux GOARCH=mips make build
          tar czvf sower-linux-mips.tar.gz sower sower.toml
          GOOS=linux GOARCH=mipsle make build
          tar czvf sower-linux-mipsle.tar.gz sower sower.toml

          GOOS=darwin GOARCH=amd64 make build
          tar czvf sower-darwin-amd64.tar.gz sower sower.toml

          GOOS=windows GOARCH=amd64 make build
          tar czvf sower-windows-amd64.tar.gz sower.exe sower.toml
          GOOS=windows GOARCH=386 make build
          tar czvf sower-windows-386.tar.gz sower.exe sower.toml

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            sower-linux-amd64.tar.gz
            sower-linux-386.tar.gz
            sower-linux-arm.tar.gz
            sower-linux-arm64.tar.gz
            sower-linux-mips.tar.gz
            sower-linux-mipsle.tar.gz
            sower-darwin-amd64.tar.gz
            sower-windows-amd64.tar.gz
            sower-windows-386.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
